#!/usr/bin/env python3
"""
Export the frames for the SVG renderer, to the Crimson Moon contract.

Three rules taken from the existing banner, and one added by this piece:

  1. ONE fixed palette across every frame, and NO DITHERING. Dithering is
     strictly worse here -- measured mean dE 3.21 with Floyd-Steinberg against
     2.78 without, at the same colour count -- and its noise is what dissolved
     the readout labels entirely at 512x256.
  2. Fully opaque. No alpha channel anywhere.
  3. No text baked in. GitHub proxies README images through Camo, which blocks
     every external resource, so the renderer draws glyphs as SVG <rect>s.
  4. NEW: this art is a graded render, not flat pixel art. The moon lives on
     10-16 colours because it is flat; grading needs an order of magnitude more.

Layers are DELTA-CROPPED. The renderer stacks frames with cumulative opacity --
frame 0 stays opaque and each later frame fades in on top and stays -- so a later
layer only has to carry the rectangle that actually changed.
"""
import argparse, base64, io, json, os
import imagequant
import numpy as np
from PIL import Image


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--w', type=int, default=384)
    p.add_argument('--h', type=int, default=192)
    p.add_argument('--colours', type=int, default=128)
    p.add_argument('--thresh', type=int, default=6, help='per-pixel delta that counts as changed')
    p.add_argument('--out', default='dist')
    a = p.parse_args()
    os.makedirs(a.out, exist_ok=True)

    stems = ['f%d' % i for i in range(1, 7)]
    small = [Image.open('build/%s.png' % s).convert('RGB').resize((a.w, a.h), Image.LANCZOS)
             for s in stems]

    strip = Image.new('RGB', (a.w, a.h * len(small)))
    for i, im in enumerate(small):
        strip.paste(im, (0, i * a.h))
    #  libimagequant, not PIL's median cut. It refines the palette with K-means
    #  (Voronoi iteration) toward a locally optimal set instead of stopping at the
    #  median-cut split, and it is measurably less posterised here: dE 1.483
    #  against 1.688 at the same colour count and the same file size.
    pal = imagequant.quantize_pil_image(strip, dithering_level=0.0,
                                        max_colors=a.colours,
                                        min_quality=0, max_quality=100)

    quant = [im.quantize(palette=pal, dither=Image.NONE) for im in small]
    arrs = [np.array(q.convert('RGB')).astype(np.int16) for q in quant]

    layers, total = [], 0
    for i, q in enumerate(quant):
        if i == 0:
            box = (0, 0, a.w, a.h)
        else:
            #  Every layer is a delta against its predecessor, because the whole
            #  15-frame sequence loops as ONE cumulative pass: within a cycle layers
            #  only ever switch ON, in order, and all of them reset together at the
            #  wrap. f01 stays permanently opaque underneath, so the reset never
            #  exposes the page ground -- no black flash.
            d = np.abs(arrs[i] - arrs[i - 1]).max(2)
            ys, xs = np.nonzero(d > a.thresh)
            if len(xs) == 0:
                layers.append(None); continue
            box = (int(xs.min()), int(ys.min()), int(xs.max()) + 1 - int(xs.min()),
                   int(ys.max()) + 1 - int(ys.min()))
        crop = q.crop((box[0], box[1], box[0] + box[2], box[1] + box[3]))
        buf = io.BytesIO(); crop.save(buf, 'PNG', optimize=True)
        raw = buf.getvalue(); total += len(raw)
        layers.append({'x': box[0], 'y': box[1], 'w': box[2], 'h': box[3],
                       'data': base64.b64encode(raw).decode()})
        crop.save('%s/%s.png' % (a.out, stems[i]), optimize=True)

    js = ('// Auto-generated by piskel_frames/plague-doctor/export.py -- do not hand-edit.\n'
          '// 15-frame "The Indifferent World" streak banner, %dx%d native, %d-colour\n'
          '// shared palette, no dithering, fully opaque. Layers after the first are\n'
          '// DELTA-CROPPED: each carries only the rectangle that changed, and the\n'
          '// renderer stacks them with cumulative opacity so earlier layers show through.\n'
          'export const ART_W = %d;\nexport const ART_H = %d;\n'
          'export const LAYERS = %s;\n' % (a.w, a.h, a.colours, a.w, a.h,
                                           json.dumps(layers, separators=(',', ':'))))
    open('%s/frames.js' % a.out, 'w').write(js)

    cov = np.mean([l['w'] * l['h'] / (a.w * a.h) for l in layers[1:] if l])
    print('  %dx%d, %d colours, no dither' % (a.w, a.h, a.colours))
    print('  %d layers, mean layer covers %.0f%% of canvas' % (len([l for l in layers if l]), cov * 100))
    print('  payload %.0f KB raw -> %.0f KB base64 in the SVG' % (total / 1024, total * 4 / 3 / 1024))
    print('  wrote %s/frames.js (%.0f KB)' % (a.out, os.path.getsize('%s/frames.js' % a.out) / 1024))


if __name__ == '__main__':
    main()
